using LittleAGames.PFWolf.SDK.FileLoaders;

namespace LittleAGames.PFWolf.FileManager.Constants.GamePacks;

public class Wolfenstein3DApogee : GamePack
{
    public const string AudioHed = "audiohed.wl6";
    public const string AudioT = "audiot.wl6";
    public const string GameMaps = "gamemaps.wl6";
    public const string MapHead = "maphead.wl6";
    public const string VgaDict = "vgadict.wl6";
    public const string VgaGraph = "vgagraph.wl6";
    public const string VgaHead = "vgahead.wl6";
    public const string Vswap = "vswap.wl6";
    
    public override string PackName => "Wolfenstein 3D v1.4 Apogee";
    
    protected override List<GamePackFile> Files => [
        new(AudioHed, "a41af25a2f193e7d4afbcc4301b3d1ce"),
        new(AudioT, "2385b488b18f8721633e5b2bdf054853"),
        new(GameMaps, "a4e73706e100dc0cadfb02d23de46481"),
        new(MapHead, "b8d2a78bc7c50da7ec9ab1d94f7975e1"),
        new(VgaDict, "adb10b0d6fdddba9fcc3d1a7c16937e7"),
        new(VgaGraph, "4e96d7b4e89a5b3a4beeebf5d7d87eb7"),
        new(VgaHead, "a08905e2b0d299b3fad259f90c0efb1a"),
        new(Vswap, "a6d901dfb455dfac96db5e4705837cdb")
    ];

    protected override List<GamePackFileLoader> FileLoaders =>
    [
        new(typeof(Wolf3DAudioFileLoader), AudioAssetReferences, AudioHed, AudioT),
        new(typeof(Wolf3DMapFileLoader), MapAssetReferences, MapHead, GameMaps),
        new(typeof(Wolf3DVgaFileLoader), GraphicAssetReferences, VgaDict, VgaHead, VgaGraph),
        new(typeof(Wolf3DVswapFileLoader), SwapAssetReferences, Vswap),
    ];

    public readonly List<string> AudioAssetReferences = [];
    public readonly List<string> MapAssetReferences = [];
    public readonly List<string> GraphicAssetReferences = [
        "STRUCTPIC", // 0
        "SmallFont",
        "LargeFont",
        "H_BJ",
        "H_Castle",
        "H_Keyboard",
        "H_Joy",
        "H_Heal",
        "H_Treasure",
        "H_Gun",
        "H_Key",
        "H_Blaze",
        "H_Weapon1234",
        "H_WolfLogo",
        "H_Visa",
        "H_MasterCard",
        "H_IDLogo",
        "H_TopWindow",
        "H_LeftWindow",
        "H_RightWindow",
        "H_BottomInfo",
        "H_SpearAd",
        "C_Options",
        "C_Cursor1",
        "C_Cursor2",
        "C_NotSelected",
        "C_Selected",
        "C_FxTitle",
        "C_DigiTitle",
        "C_MusicTitle",
        "C_MouseLBack",
        "C_BabyMode",
        "C_Easy",
        "C_Normal",
        "C_Hard",
        "C_LoadSaveDisk",
        "C_DiskLoading1",
        "C_DiskLoading2",
        "C_Control",
        "C_Customize",
        "C_LoadGame",
        "C_SaveGame",
        "C_Episode1",
        "C_Episode2",
        "C_Episode3",
        "C_Episode4",
        "C_Episode5",
        "C_Episode6",
        "C_Code",
        "C_TimeCode",
        "C_Level",
        "C_Name",
        "C_Score",
        "C_Joy1",
        "C_Joy2",
        "L_Guy",
        "L_Colon",
        "L_Num0",
        "L_Num1",
        "L_Num2",
        "L_Num3",
        "L_Num4",
        "L_Num5",
        "L_Num6",
        "L_Num7",
        "L_Num8",
        "L_Num9",
        "L_Percent",
        "L_A",
        "L_B",
        "L_C",
        "L_D",
        "L_E",
        "L_F",
        "L_G",
        "L_H",
        "L_I",
        "L_J",
        "L_K",
        "L_L",
        "L_M",
        "L_N",
        "L_O",
        "L_P",
        "L_Q",
        "L_R",
        "L_S",
        "L_T",
        "L_U",
        "L_V",
        "L_W",
        "L_X",
        "L_Y",
        "L_Z",
        "L_ExclamationPoint",
        "L_Apostrophe",
        "L_Guy2",
        "L_BJWins",
        "StatusBar",
        "Title",
        "PG13",
        "Credits",
        "HighScores",
        "Knife",
        "Gun",
        "MachineGun",
        "GatlingGun",
        "NoKey",
        "GoldKey",
        "SilverKey",
        "N_Blank",
        "N_0",
        "N_1",
        "N_2",
        "N_3",
        "N_4",
        "N_5",
        "N_6",
        "N_7",
        "N_8",
        "N_9",
        "Face1A",
        "Face1B",
        "Face1C",
        "Face2A",
        "Face2B",
        "Face2C",
        "Face3A",
        "Face3B",
        "Face3C",
        "Face4A",
        "Face4B",
        "Face4C",
        "Face5A",
        "Face5B",
        "Face5C",
        "Face6A",
        "Face6B",
        "Face6C",
        "Face7A",
        "Face7B",
        "Face7C",
        "Face8A",
        "GotGatling",
        "MutantBJ",
        "Paused",
        "GetPsyched",
        "Tile8",
        "OrderScreen",
        "ErrorScreen",
        "HelpArt",
        "Demo0",
        "Demo1",
        "Demo2",
        "Demo3",
        "EndArt1",
        "EndArt2",
        "EndArt3",
        "EndArt4",
        "EndArt5",
        "EndArt6"
    ];
    
    public readonly List<string> SwapAssetReferences = [];
}